Se refactorizo en la parte visual algunos componentes en la vista new…
BC-MAY-21-ROR/proyecto-final-SAPE-m22-pf-t2 pull request #112
Opened 2022-08-15 05:25 UTC by ever864

Muchachos refactoricen mi PR y mi commit porfa, lo hice rapido. Hice solo algunos cambios nada interesante, no tenia mucho tiempo. Tambien burre una migracion para que me funcione la app, no entendia muy bien eso para poder arreglarlo.

2022-08-15 22:28 UTC, YilKanda requested changes

2022-08-15 22:28 UTC, YilKanda commented on app/controllers/application_controller.rb
> +  end
Why do you use this method?

2022-08-15 22:29 UTC, YilKanda commented on app/controllers/application_controller.rb
> +  end
Resolve your conflicts in your branches.

2022-08-16 23:33 UTC, YilKanda approved these changes
LGTM!

2022-08-17 13:48 UTC, juperameza approved these changes
LGTM! Just resolve your conflicts

2022-08-17 23:00 UTC, closed without merging